### ISSUE TITLE
ssh: Could not resolve hostname github.com: Name or service not known

### ISSUE THREAD

**Issue by pigeonmed** [blankogmbh/kirby-git-commit-and-push-content#15]
I have setup ssh keys for my github repository and `ssh -T git@github.com` works, however, I'm getting the following error when I make a GET request at the /gcapc/push endpoint.

```
2016/07/07 22:40:54 [error] 44#44: *63 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
' in /pigeon-website/site/plugins/git-commit-and-push-content/Git.php/Git.php:317
Stack trace:
#0 /pigeon-website/site/plugins/git-commit-and-push-content/Git.php/Git.php(332): GitRepo->run_command('/usr/bin/git pu...')
#1 /pigeon-website/site/plugins/git-commit-and-push-content/Git.php/Git.php(627): GitRepo->run('push --tags ori...')
#2 /pigeon-website/site/plugins/git-commit-and-push-content/helpers.php(64): GitRepo->push('origin', 'master')
#3 /pigeon-website/site/plugins/git-commit-and-push-content/git-commit-and-push-content.php(80): KirbyGitHelper->push()
#4 [internal function]: Kirby->{closure}('push')
#5 /pigeon-website/kirby/toolkit/helpers.php(270): call_user_func_array(Object(Closure), Array)
#6 /pigeon-website/kirby/kirby.php" while reading response header from upstream, client: 10.0.2.2, server: _, request: "GET /gcapc/push HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "localhost:8005"
10.0.2.2 - - [07/Jul/2016:22:40:54 +0000] "GET /gcapc/push HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
```

If it helps here is the output of `git config --list`:

```
user.name=pigeonmed
user.email=<my_email_address>
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:pigeonmed/pigeon-website.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
submodule.git-commit-and-push-content.url=https://github.com/pigeonmed/kirby-git-commit-and-push-content.git
root@8695cdc269c4:/pigeon-website# git remote -v
origin	git@github.com:pigeonmed/pigeon-website.git (fetch)
origin	git@github.com:pigeonmed/pigeon-website.git (push)
```

I figure this is probably a configuration issue on my end but I have yet to track it down. Have you seen anything like this before?

**Comment by pigeonmed** [comment]
Turns out the issue was related to running my Kirby website in a docker container. The solution was to update my ~/.ssh/config so that it included a hostname and port number:

```
Host github.com
  Hostname ssh.github.com
  Port 443 
```
